CREATE TABLE IF NOT EXISTS ea_rag_sparse_term (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    rag_source_id BIGINT NOT NULL,
    rag_chunk_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    project_id BIGINT NULL,
    session_id BIGINT NOT NULL DEFAULT 0,
    scope_type VARCHAR(16) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    source_id BIGINT NOT NULL,
    term VARCHAR(128) NOT NULL,
    field_code VARCHAR(16) NOT NULL,
    term_freq INT NOT NULL DEFAULT 1,
    doc_len INT NOT NULL DEFAULT 0,
    created_by BIGINT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_ea_rag_sparse_term_chunk_field_term (rag_chunk_id, field_code, term),
    KEY idx_ea_rag_sparse_term_source (rag_source_id, rag_chunk_id),
    KEY idx_ea_rag_sparse_term_lookup (scope_type, owner_user_id, term, source_type, project_id, session_id),
    KEY idx_ea_rag_sparse_term_source_ref (source_type, source_id, session_id)
);
