CREATE TABLE IF NOT EXISTS approval_request (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  request_id VARCHAR(128) NOT NULL,
  session_id BIGINT NULL,
  initiated_user_id BIGINT NOT NULL,
  confirmed_user_id BIGINT NULL,
  executed_user_id BIGINT NULL,
  org_id BIGINT NOT NULL DEFAULT 0,
  project_id BIGINT NULL,
  action_code VARCHAR(64) NOT NULL,
  target_type VARCHAR(32) NULL,
  target_id BIGINT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  risk_level VARCHAR(32) NOT NULL DEFAULT 'HIGH',
  plan_summary VARCHAR(1000) NOT NULL,
  request_payload_json LONGTEXT NULL,
  params_json LONGTEXT NULL,
  resource_snapshot_json LONGTEXT NULL,
  result_payload_json LONGTEXT NULL,
  error_code VARCHAR(64) NULL,
  error_message VARCHAR(500) NULL,
  confirmed_at DATETIME NULL,
  executed_at DATETIME NULL,
  expires_at DATETIME NULL,
  latency_ms INT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_approval_request_request (request_id),
  KEY idx_approval_request_session (session_id),
  KEY idx_approval_request_user_status (initiated_user_id, status),
  KEY idx_approval_request_project (project_id),
  KEY idx_approval_request_action (action_code, status)
);

CREATE TABLE IF NOT EXISTS admin_action_request (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  approval_request_id BIGINT NOT NULL,
  request_id VARCHAR(128) NOT NULL,
  initiated_user_id BIGINT NOT NULL,
  confirmed_user_id BIGINT NULL,
  executed_user_id BIGINT NULL,
  action_code VARCHAR(64) NOT NULL,
  action_status VARCHAR(32) NOT NULL,
  target_type VARCHAR(32) NULL,
  target_id BIGINT NULL,
  audit_payload_json LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_admin_action_approval (approval_request_id),
  KEY idx_admin_action_request (request_id),
  KEY idx_admin_action_initiator (initiated_user_id),
  KEY idx_admin_action_status (action_code, action_status)
);
