CREATE TABLE IF NOT EXISTS ea_rag_source (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    owner_user_id BIGINT NOT NULL,
    project_id BIGINT NULL,
    session_id BIGINT NOT NULL DEFAULT 0,
    scope_type VARCHAR(16) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    source_id BIGINT NOT NULL,
    source_title VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    content_hash VARCHAR(64) NULL,
    chunk_count INT NOT NULL DEFAULT 0,
    last_indexed_at DATETIME NULL,
    last_error VARCHAR(1000) NULL,
    embedding_model_code VARCHAR(128) NULL,
    embedding_version VARCHAR(64) NULL,
    embedding_dimension INT NULL,
    created_by BIGINT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_ea_rag_source_scope (owner_user_id, scope_type, source_type, source_id, session_id),
    KEY idx_ea_rag_source_owner_project (owner_user_id, project_id, status),
    KEY idx_ea_rag_source_owner_session (owner_user_id, session_id, status)
);

CREATE TABLE IF NOT EXISTS ea_rag_chunk (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    rag_source_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    project_id BIGINT NULL,
    session_id BIGINT NOT NULL DEFAULT 0,
    source_type VARCHAR(32) NOT NULL,
    source_id BIGINT NOT NULL,
    chunk_num INT NOT NULL DEFAULT 0,
    chunk_text LONGTEXT NOT NULL,
    page_no INT NULL,
    section_path VARCHAR(255) NULL,
    vector_collection VARCHAR(64) NOT NULL,
    vector_point_id VARCHAR(64) NOT NULL,
    embedding_model_code VARCHAR(128) NULL,
    embedding_version VARCHAR(64) NULL,
    embedding_dimension INT NULL,
    created_by BIGINT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_ea_rag_chunk_source_chunk (rag_source_id, chunk_num),
    KEY idx_ea_rag_chunk_owner_project (owner_user_id, project_id, source_type, source_id),
    KEY idx_ea_rag_chunk_session_source (owner_user_id, session_id, source_type, source_id),
    FULLTEXT KEY ft_ea_rag_chunk_text (chunk_text(1000))
);

CREATE TABLE IF NOT EXISTS ea_rag_task (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    owner_user_id BIGINT NOT NULL,
    project_id BIGINT NULL,
    session_id BIGINT NOT NULL DEFAULT 0,
    rag_source_id BIGINT NULL,
    task_type VARCHAR(32) NOT NULL DEFAULT 'INDEX',
    task_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    scope_type VARCHAR(16) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    source_id BIGINT NOT NULL,
    retry_count INT NOT NULL DEFAULT 0,
    payload_json LONGTEXT NULL,
    result_json LONGTEXT NULL,
    last_error VARCHAR(1000) NULL,
    created_by BIGINT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    KEY idx_ea_rag_task_owner_status (owner_user_id, task_status, created_at),
    KEY idx_ea_rag_task_source (scope_type, source_type, source_id, session_id)
);
