-- Consolidated AI Assistant MySQL schema.
-- Backend Flyway migrations in erise-ai-backend/src/main/resources/db/migration
-- remain the canonical upgrade path. This file is for manual bootstrap/reference.

CREATE TABLE IF NOT EXISTS ai_chat_session (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    org_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT NULL,
    scene VARCHAR(32) NOT NULL,
    title VARCHAR(255) NOT NULL,
    summary_text TEXT NULL,
    last_message_at DATETIME(6) NULL,
    message_count INT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_ai_chat_session_user_id (user_id),
    KEY idx_ai_chat_session_project_id (project_id),
    KEY idx_ai_chat_session_last_message_at (last_message_at),
    KEY idx_ai_chat_session_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_chat_message (
    id BIGINT NOT NULL AUTO_INCREMENT,
    session_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(32) NOT NULL,
    content TEXT NOT NULL,
    content_format VARCHAR(32) NOT NULL DEFAULT 'text',
    message_status VARCHAR(32) NOT NULL DEFAULT 'success',
    sequence_no INT NOT NULL,
    model_code VARCHAR(128) NULL,
    provider_code VARCHAR(64) NULL,
    confidence DOUBLE NULL,
    refused_reason VARCHAR(255) NULL,
    citations_json TEXT NULL,
    used_tools_json TEXT NULL,
    answer_source VARCHAR(64) NULL,
    prompt_tokens INT NULL,
    completion_tokens INT NULL,
    total_tokens INT NULL,
    latency_ms INT NULL,
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(500) NULL,
    request_id VARCHAR(128) NULL,
    parent_message_id BIGINT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_ai_chat_message_session_id (session_id),
    KEY idx_ai_chat_message_user_id (user_id),
    KEY idx_ai_chat_message_status (message_status),
    KEY idx_ai_chat_message_request_id (request_id),
    KEY idx_ai_chat_message_session_sequence (session_id, sequence_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_request_log (
    id BIGINT NOT NULL AUTO_INCREMENT,
    request_id VARCHAR(128) NOT NULL,
    session_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL DEFAULT 0,
    org_id BIGINT NOT NULL DEFAULT 0,
    project_id BIGINT NULL,
    user_message_id BIGINT NULL,
    assistant_message_id BIGINT NULL,
    provider_code VARCHAR(64) NOT NULL,
    model_code VARCHAR(128) NOT NULL,
    scene VARCHAR(32) NOT NULL,
    temperature DOUBLE NULL,
    max_tokens INT NULL,
    stream BOOLEAN NOT NULL DEFAULT FALSE,
    request_payload_json TEXT NULL,
    response_payload_json TEXT NULL,
    answer_source VARCHAR(64) NULL,
    message_status VARCHAR(32) NULL,
    input_token_count INT NULL,
    output_token_count INT NULL,
    total_token_count INT NULL,
    latency_ms INT NULL,
    duration_ms INT NULL,
    success_flag BOOLEAN NOT NULL DEFAULT FALSE,
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(500) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_ai_request_log_request_id (request_id),
    KEY idx_ai_request_log_session_id (session_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_prompt_template (
    id BIGINT NOT NULL AUTO_INCREMENT,
    template_code VARCHAR(128) NOT NULL,
    template_name VARCHAR(255) NOT NULL,
    scene VARCHAR(32) NOT NULL,
    system_prompt TEXT NOT NULL,
    user_prompt_wrapper TEXT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    version_no INT NOT NULL DEFAULT 1,
    created_by VARCHAR(64) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_prompt_template_code_version (template_code, version_no),
    KEY idx_ai_prompt_template_scene (scene),
    KEY idx_ai_prompt_template_code_enabled (template_code, enabled, version_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_model_config (
    id BIGINT NOT NULL AUTO_INCREMENT,
    provider_code VARCHAR(64) NOT NULL,
    model_code VARCHAR(128) NOT NULL,
    model_name VARCHAR(255) NOT NULL,
    base_url VARCHAR(255) NULL,
    api_key_ref VARCHAR(64) NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    is_default TINYINT(1) NOT NULL DEFAULT 0,
    support_stream BOOLEAN NOT NULL DEFAULT TRUE,
    support_system_prompt BOOLEAN NOT NULL DEFAULT TRUE,
    max_context_tokens INT NULL,
    input_price_per_million DECIMAL(12,4) NULL,
    output_price_per_million DECIMAL(12,4) NULL,
    currency_code VARCHAR(16) NOT NULL DEFAULT 'USD',
    priority_no INT NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_model_config_model_code (model_code),
    KEY idx_ai_model_config_provider_priority (provider_code, priority_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_message_citation (
    id BIGINT NOT NULL AUTO_INCREMENT,
    message_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    position_no INT NOT NULL DEFAULT 0,
    source_type VARCHAR(32) NOT NULL,
    source_id BIGINT NOT NULL,
    source_title VARCHAR(255) NOT NULL,
    snippet TEXT NULL,
    page_no INT NULL,
    section_path VARCHAR(255) NULL,
    score DOUBLE NULL,
    url VARCHAR(1000) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_ai_message_citation_message_id (message_id),
    KEY idx_ai_message_citation_session_id (session_id),
    KEY idx_ai_message_citation_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_action_log (
    id BIGINT NOT NULL AUTO_INCREMENT,
    request_id VARCHAR(128) NOT NULL,
    session_id BIGINT NULL,
    user_id BIGINT NOT NULL,
    org_id BIGINT NOT NULL,
    project_id BIGINT NULL,
    action_code VARCHAR(64) NOT NULL,
    match_rule VARCHAR(128) NOT NULL,
    permission_rule VARCHAR(128) NOT NULL,
    action_status VARCHAR(32) NOT NULL,
    target_type VARCHAR(32) NULL,
    target_id BIGINT NULL,
    model_code VARCHAR(128) NULL,
    provider_code VARCHAR(64) NULL,
    params_json LONGTEXT NULL,
    result_payload_json LONGTEXT NULL,
    fallback_message VARCHAR(500) NULL,
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(500) NULL,
    latency_ms INT NULL,
    success_flag TINYINT NOT NULL DEFAULT 0,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_ai_action_log_request (request_id),
    KEY idx_ai_action_log_session (session_id),
    KEY idx_ai_action_log_action_status (action_code, action_status),
    KEY idx_ai_action_log_user_created (user_id, created_at DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_message_feedback (
    id BIGINT NOT NULL AUTO_INCREMENT,
    message_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    feedback_type VARCHAR(16) NOT NULL,
    feedback_note VARCHAR(500) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_message_feedback_message_user (message_id, user_id),
    KEY idx_ai_message_feedback_user_created (user_id, created_at DESC),
    KEY idx_ai_message_feedback_type_created (feedback_type, created_at DESC),
    KEY idx_ai_message_feedback_session (session_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS n8n_event_log (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    request_id VARCHAR(128) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    workflow_hint VARCHAR(128) NULL,
    approval_id BIGINT NULL,
    session_id BIGINT NULL,
    user_id BIGINT NULL,
    project_id BIGINT NULL,
    target_url VARCHAR(1000) NULL,
    delivery_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    workflow_status VARCHAR(64) NULL,
    workflow_name VARCHAR(128) NULL,
    workflow_version VARCHAR(32) NULL,
    workflow_domain VARCHAR(64) NULL,
    workflow_owner VARCHAR(128) NULL,
    external_execution_id VARCHAR(128) NULL,
    workflow_error_summary VARCHAR(500) NULL,
    workflow_duration_ms INT NULL,
    delivery_retryable TINYINT NOT NULL DEFAULT 0,
    manual_status VARCHAR(32) NULL,
    manual_reason VARCHAR(500) NULL,
    manual_replay_count INT NOT NULL DEFAULT 0,
    replayed_from_event_id BIGINT NULL,
    last_callback_at DATETIME NULL,
    status_code INT NULL,
    success_flag TINYINT NOT NULL DEFAULT 0,
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(500) NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    max_attempts INT NOT NULL DEFAULT 1,
    idempotency_key VARCHAR(255) NULL,
    signature VARCHAR(128) NULL,
    payload_json LONGTEXT NULL,
    callback_payload_json LONGTEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_n8n_event_request (request_id),
    KEY idx_n8n_event_type (event_type),
    KEY idx_n8n_event_workflow (workflow_hint),
    KEY idx_n8n_event_delivery_status (delivery_status, created_at),
    KEY idx_n8n_event_workflow_status (workflow_status, created_at),
    KEY idx_n8n_event_idempotency_key (idempotency_key),
    KEY idx_n8n_event_workflow_name (workflow_name, created_at),
    KEY idx_n8n_event_external_execution (external_execution_id),
    KEY idx_n8n_event_manual_status (manual_status, created_at),
    KEY idx_n8n_event_replayed_from (replayed_from_event_id),
    KEY idx_n8n_event_last_callback (last_callback_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
