CREATE TABLE IF NOT EXISTS ai_message_citation (
    id BIGINT NOT NULL AUTO_INCREMENT,
    message_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    position_no INT NOT NULL DEFAULT 0,
    source_type VARCHAR(32) NOT NULL,
    source_id BIGINT NOT NULL,
    source_title VARCHAR(255) NOT NULL,
    snippet TEXT NULL,
    page_no INT NULL,
    score DOUBLE NULL,
    url VARCHAR(1000) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_ai_message_citation_message_id (message_id),
    KEY idx_ai_message_citation_session_id (session_id),
    KEY idx_ai_message_citation_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
